# OSAWS - Avatar Picker
server {
    listen 80;
    server_name avatarpicker.main.examplegrid.com;
    root /var/www/osaws;

    index avatarpicker.php;

    location / {
        try_files $uri $uri/ /avatarpicker.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

# OSAWS - Viewer Asset
server {
    listen 80;
    server_name viewerassets.main.examplegrid.com;
    root /var/www/osaws;

    index viewerassets.php;

    location / {
        try_files $uri $uri/ /viewerassets.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

# OSAWS - FS Assets
server {
    listen 80;
    server_name assets.main.examplegrid.com;
    root /var/www/osaws;

    index fsassets.php;

    location / {
        try_files $uri $uri/ /fsassets.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

# OSAWS - LSL Syntax
server {
    listen 80;
    server_name lslsyntax.main.examplegrid.com;
    root /var/www/osaws;

    index lslsyntax.php;

    location / {
        try_files $uri $uri/ /lslsyntax.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
